Description: >
    Rudi Thoma / Udacity Capstone project
    This template deploys a VPC, with a pair of public subnets spread 
    across two Availabilty Zones. It deploys an Internet Gateway, with a default 
    route on the public subnets.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    VpcCIDR: 
        Description: Please enter the IP range (CIDR notation) for this VPC
        Type: String
        Default: 10.0.0.0/16

    EksRole:
        Description: Role Assigned to the EKS Cluster
        Type: String
        Default: arn:aws:iam::243572158472:role/eksClusterRole

    EksNodeGroupeRole:
        Description: Role Assigned to the EKS NodeGroup
        Type: String
        Default: arn:aws:iam::243572158472:role/NodeInstanceRole

Resources:

  EksSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: EKS Cluster Security Group
      Tags: 
        - Key: Environment
          Value: !Ref EnvironmentName
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"

  EksSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref EksSecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref EksSecurityGroup

  EksCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: EksCluster
      Version: '1.15'
      RoleArn: !Ref EksRole
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EksSecurityGroup
        SubnetIds:
          - Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
          - Fn::ImportValue: !Sub "${EnvironmentName}-PUB2-SN"

  EksNodeGroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: !Ref EksCluster
      NodeRole: !Ref EksNodeGroupeRole
      ScalingConfig:
        MinSize: 1
        DesiredSize: 1
        MaxSize: 3
      Subnets:
        - Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
        - Fn::ImportValue: !Sub "${EnvironmentName}-PUB2-SN"
